# Generated by Django 3.2.9 on 2021-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serialnumber', models.CharField(db_column='serialnumber', max_length=300, primary_key=True, serialize=False, verbose_name='裝置序列號')),
                ('model', models.CharField(db_column='model', max_length=128, serialize=False, verbose_name='裝置型號')),
                ('name', models.CharField(db_column='name', max_length=128, serialize=False, verbose_name='裝置名稱')),
                ('bind', models.IntegerField(choices=[(1, 'BIND'), (0, 'UNBIND')], db_column='bind', null=True, verbose_name='是否綁定')),
            ],
        ),
    ]
