# Generated by Django 3.2.9 on 2021-11-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(db_column='model', max_length=128, null=True, serialize=False, verbose_name='裝置型號'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(db_column='name', max_length=128, null=True, serialize=False, verbose_name='裝置名稱'),
        ),
    ]
