# Generated by Django 3.2.9 on 2021-11-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(db_column='email', max_length=160, primary_key=True, serialize=False),
        ),
    ]
